language: node_js
cache:
  directories:
    - node_modules
    - ~/np,
node_js:
  - 14.17.6
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "proyect deploy"
  on:
    branch: master
